services:

  postgres-server:
    image: postgres:15
    container_name: ${KEYCLOAK_DB_HOST}
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "9292:5432"
    networks:
      - ethicpay-network

  keycloak-server:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: ${KEYCLOAK_HOST}
    command: start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Hostname Configuration
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
#      KC_HOSTNAME_BACKCHANNEL_DYNAMIC : rue
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres-server
    networks:
      - ethicpay-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80" # accès via http://localhost:8081
    depends_on:
      - postgres-server
    networks:
      - ethicpay-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin


networks:
  ethicpay-network:
    external: true
    driver: bridge

volumes:
  kc_postgres_data:
  pgdata:
  pgadmin-data:
  es_data:
  ethicpay-shared-logs:
    external: true